# TCL File Generated by Component Editor 21.3
# Wed Oct 11 15:13:16 BST 2023
# DO NOT MODIFY


# 
# FiveAlive "FiveAlive" v1.0
#  2023.10.11.15:13:16
# 
# 

# 
# request TCL package from ACDS 21.3
# 
package require -exact qsys 21.3


# 
# module FiveAlive
# 
set_module_property DESCRIPTION ""
set_module_property NAME FiveAlive
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FiveAlive
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FiveAlive
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FiveAlive.v VERILOG PATH ../FiveAlive.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clock clk Input 1


# 
# connection point jtaguart_master
# 
add_interface jtaguart_master avalon start
set_interface_property jtaguart_master addressGroup 0
set_interface_property jtaguart_master addressUnits SYMBOLS
set_interface_property jtaguart_master associatedClock clock
set_interface_property jtaguart_master associatedReset reset
set_interface_property jtaguart_master bitsPerSymbol 8
set_interface_property jtaguart_master burstOnBurstBoundariesOnly false
set_interface_property jtaguart_master burstcountUnits WORDS
set_interface_property jtaguart_master doStreamReads false
set_interface_property jtaguart_master doStreamWrites false
set_interface_property jtaguart_master holdTime 0
set_interface_property jtaguart_master linewrapBursts false
set_interface_property jtaguart_master maximumPendingReadTransactions 0
set_interface_property jtaguart_master maximumPendingWriteTransactions 0
set_interface_property jtaguart_master minimumResponseLatency 1
set_interface_property jtaguart_master readLatency 0
set_interface_property jtaguart_master readWaitTime 1
set_interface_property jtaguart_master setupTime 0
set_interface_property jtaguart_master timingUnits Cycles
set_interface_property jtaguart_master waitrequestAllowance 0
set_interface_property jtaguart_master writeWaitTime 0
set_interface_property jtaguart_master ENABLED true
set_interface_property jtaguart_master EXPORT_OF ""
set_interface_property jtaguart_master PORT_NAME_MAP ""
set_interface_property jtaguart_master CMSIS_SVD_VARIABLES ""
set_interface_property jtaguart_master SVD_ADDRESS_GROUP ""
set_interface_property jtaguart_master IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port jtaguart_master in0_avl_jtaguart_readdata readdata Input 32
add_interface_port jtaguart_master in0_avl_jtaguart_waitrequest waitrequest Input 1
set_port_property in0_avl_jtaguart_waitrequest VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port jtaguart_master out_avl_jtaguart_read read Output 1
set_port_property out_avl_jtaguart_read VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port jtaguart_master out_avl_jtaguart_write write Output 1
set_port_property out_avl_jtaguart_write VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port jtaguart_master out_avl_jtaguart_writedata writedata Output 32
add_interface_port jtaguart_master out_avl_jtaguart_address address Output 3

